### PR TITLE
Added DNS as variables

### PR DESCRIPTION
**Pull request by tomsherrod**
Enable DNS as variables for change.

(First github pull request.)

### CODE REVIEW

**Comment by Zouuup** [comment]
+1

**Comment by lnguyen** [comment]
Lgtm

**Comment by lnguyen** [comment]
@tomfuie can you rebase with master? then we can merge it

**Comment by tomsherrod** [comment]
I think the rebase is done. Let me know of issues.

**Comment by lnguyen** [comment]
can you push @tomfuie doesn't look like it went thru

**Comment by tomsherrod** [comment]
I'm getting all clean/everything up-to-date.
Would it be easier to wipe it all/delete fork and start a fresh?  One reason I made my first change a small one.

**Comment by lnguyen** [comment]
might be, sorry about this

**Comment by lnguyen** [comment]
I fixed merge conflict on https://github.com/cloudfoundry-community/terraform-openstack-cf-install/pull/35 will merge in when test past

**Pull request closed without merging**
